version: "3.5"
services:

  redis:
    container_name: redis
    image: redis:4.0.11
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
    - "6379:6379"

#  message-api:
#      container_name: message-api
#      image: message-api:1.0.0
#      hostname: message-api
#      ports:
#      - "8080:8080"
#      depends_on:
#      - redis
#
#  message-dispatcher:
#      container_name: message-dispatcher
#      image: message-dispatcher:1.0.0
#      hostname: message-dispatcher
#      depends_on:
#      - redis
#      - message-api
#
#  message-router:
#      container_name: message-router
#      image: message-router:1.0.0
#      hostname: message-router
#      depends_on:
#      - redis
#      - message-api
#
#  message-processor-echo:
#      container_name: message-processor-echo
#      image: message-processor-echo:1.0.0
#      hostname: message-processor-echo
#      depends_on:
#      - redis
#      - message-router
#
#  message-processor-joke:
#      container_name: message-processor-joke
#      image: message-processor-joke:1.0.0
#      hostname: message-processor-joke
#      depends_on:
#      - redis
#      - message-router
#
#  message-processor-reverse:
#      container_name: message-processor-reverse
#      image: message-processor-reverse:1.0.0
#      hostname: message-processor-reverse
#      depends_on:
#      - redis
#      - message-router

networks:
  default:
    name: telegram-microservices