consumers:
    size: 1

redis:
    host: localhost
    port: 6379
    max-clients: 5
    collection:
        bot: bot
    queue:
        router: message-router
        processor-echo: message-processor-echo
        processor-joke: message-processor-joke
        processor-reverse: message-processor-reverse

---

spring:
    profiles: docker

redis:
    host: redis
