consumers:
    size: 1

redis:
    host: localhost
    port: 6379
    max-clients: 10
    collection:
        bot: bot
    queue:
        dispatcher: message-dispatcher

---

spring:
    profiles: docker

redis:
    host: redis
